CREATE TABLE noteful_notes (
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT,
    folder_id INTEGER
        REFERENCES noteful_folders(folder_id) ON DELETE CASCADE NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL
);